language: python
python:
  - "3.7.0"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./main.py
  - python -m compileall ./cogs
  - python -m compileall ./utilitie
cache: pip
notifications:
  email: false
dist: xenial
os: linux
